import math


WIDTH = 1600
HEIGHT = 900

FPS = 60

PLAYER_POS = (1.5, 5)
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

PLAYER_FOV = math.pi / 3
RAYS_NUM = WIDTH // 2
DELTA_ANGLE = PLAYER_FOV / RAYS_NUM
MAX_DEPTH = 20

SCREEN_DIST = (WIDTH // 2) / math.tan(PLAYER_FOV / 2)
SCALE = WIDTH // RAYS_NUM